'------------------------------------------------------------------------------
' <auto-generated>
'    這個程式碼是由範本產生。
'
'    對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
'    如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class area_basic
    Public Property cityarea As String
    Public Property zipcode As String
    Public Property city As String
    Public Property area As String
    Public Property ecity As String
    Public Property earea As String

End Class
