'------------------------------------------------------------------------------
' <auto-generated>
'    這個程式碼是由範本產生。
'
'    對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
'    如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class chart
    Public Property chr_no As Integer
    Public Property pt_name As String
    Public Property ac_type As String
    Public Property birth_date As String
    Public Property sex As String
    Public Property id_no As String
    Public Property add_city As String
    Public Property add_area As String
    Public Property add_road As String
    Public Property add_neb As String
    Public Property add_lane As String
    Public Property add_alley As String
    Public Property add_no As String
    Public Property add_no_desh As String
    Public Property add_floor As String
    Public Property add_floor_desh As String
    Public Property add_room As String
    Public Property zipcode As String
    Public Property cell_phone As String
    Public Property tel_no As String
    Public Property email As String
    Public Property mother_id_no As String
    Public Property last_opd_date As String
    Public Property first_opd_date As String
    Public Property last_health_date As String
    Public Property blood_type As String
    Public Property education As String
    Public Property married As String
    Public Property job As String
    Public Property pt_bh As String
    Public Property pt_bw As String
    Public Property pt_lmp As String
    Public Property sens_remark As String
    Public Property pt_remak As String
    Public Property pt_self_remark As String
    Public Property off_id As String
    Public Property ins_corp_code As String
    Public Property disc_code As String
    Public Property ic_address As String
    Public Property death_flag As String
    Public Property death_date As String
    Public Property home_care_type As String
    Public Property home_care_join_date As String

    Public Overridable Property chart1 As chart
    Public Overridable Property chart2 As chart

End Class
