'------------------------------------------------------------------------------
' <auto-generated>
'    這個程式碼是由範本產生。
'
'    對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
'    如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class hosp_basic
    Public Property hosp_ins_no As String
    Public Property hosp_type As String
    Public Property hosp_name As String
    Public Property own_name As String
    Public Property own_id As String
    Public Property hosp_address As String
    Public Property hosp_tel As String
    Public Property hosp_fax As String
    Public Property license_qty As Nullable(Of Integer)
    Public Property pharm_code As String
    Public Property reg_fee_first As Nullable(Of Decimal)
    Public Property reg_fee As Nullable(Of Decimal)
    Public Property reg_fee_diag As Nullable(Of Decimal)
    Public Property med_out_flag As String
    Public Property rec_fee_type As String
    Public Property reg_type As String
    Public Property apply_type As String
    Public Property check_in_flag As String
    Public Property doc_med As String
    Public Property apply_card_type As String
    Public Property stock_flag As String
    Public Property ds_name As String
    Public Property ds_ins_code As String
    Public Property ds_own_name As String
    Public Property ds_own_id As String
    Public Property ds_address As String
    Public Property ds_tel As String
    Public Property ds_fax As String
    Public Property doc_login As String
    Public Property doc_pwd As String
    Public Property pharm_type As String

End Class
