'------------------------------------------------------------------------------
' <auto-generated>
'    這個程式碼是由範本產生。
'
'    對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
'    如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Data.Entity
Imports System.Data.Entity.Infrastructure

Partial Public Class knEntities
    Inherits DbContext

    Public Sub New()
        MyBase.New("name=knEntities")
    End Sub

    Protected Overrides Sub OnModelCreating(modelBuilder As DbModelBuilder)
        Throw New UnintentionalCodeFirstException()
    End Sub

    Public Property chart() As DbSet(Of chart)
    Public Property hosp_basic() As DbSet(Of hosp_basic)
    Public Property area_basic() As DbSet(Of area_basic)
    Public Property road_basic() As DbSet(Of road_basic)

End Class
