'------------------------------------------------------------------------------
' <auto-generated>
'    這個程式碼是由範本產生。
'
'    對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
'    如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class 病患檔
    Public Property ts As Byte()
    Public Property Counter As Integer
    Public Property 病歷號碼 As String
    Public Property 姓名 As String
    Public Property 生日 As String
    Public Property 優免身份代碼 As Nullable(Of Short)
    Public Property 身份證字號 As String
    Public Property 婚姻代碼 As Nullable(Of Short)
    Public Property 性別代碼 As Nullable(Of Short)
    Public Property 血型代碼 As Nullable(Of Short)
    Public Property 體重 As Nullable(Of Single)
    Public Property 電話H As String
    Public Property 電話O As String
    Public Property BBC As String
    Public Property 簡碼 As String
    Public Property 過敏 As String
    Public Property 地址 As String
    Public Property 備註事項 As String
    Public Property 既往歷 As String
    Public Property 初診日期 As String
    Public Property 欠款金額 As Nullable(Of Single)
    Public Property 籍貫 As String
    Public Property 職業 As String
    Public Property 最近就診日 As String
    Public Property 最近檢驗日 As String
    Public Property 預約未到診次數 As Nullable(Of Short)
    Public Property 過敏原1 As String
    Public Property 過敏原2 As String
    Public Property 過敏原3 As String
    Public Property 過敏原4 As String
    Public Property 欠單數 As Nullable(Of Short)
    Public Property 刪除否 As Nullable(Of Short)
    Public Property 預設就診身份代碼 As Nullable(Of Short)
    Public Property 郵地區號 As String
    Public Property 單位別代碼 As Nullable(Of Short)
    Public Property 階級代碼 As Nullable(Of Short)
    Public Property 軍種代碼 As Nullable(Of Short)
    Public Property 護照號碼 As String
    Public Property 下次應診項目 As String
    Public Property 活動狀態代碼 As Nullable(Of Short)
    Public Property 經手記錄 As String
    Public Property 最近爽約日期 As String
    Public Property 死亡日期 As String
    Public Property 行動電話 As String
    Public Property 分機號碼 As String
    Public Property 傳染病 As String
    Public Property 補助證號 As String
    Public Property 重大傷病證號 As String
    Public Property 重大傷病效期 As String
    Public Property 電話O分機 As String
    Public Property 電話H分機 As String
    Public Property 外籍 As Nullable(Of Short)
    Public Property 重病卡生效日 As String
    Public Property 重病卡備註 As String
    Public Property 活動狀態歸檔日期 As String
    Public Property 在本院輸血次數累計 As Nullable(Of Short)
    Public Property 低收入戶證號 As String
    Public Property 緊急聯絡人姓名 As String
    Public Property 緊急聯絡人電話 As String
    Public Property Email帳號 As String
    Public Property 傳真電話 As String
    Public Property 最初洗腎日 As String
    Public Property 隔離起日 As String
    Public Property 隔離迄日 As String
    Public Property 病歷本院區代號 As String
    Public Property 當地居民否 As Nullable(Of Short)
    Public Property 原住民否 As Nullable(Of Short)
    Public Property 身高 As Nullable(Of Single)
    Public Property 識字否 As Nullable(Of Short)
    Public Property 修改日期時間 As String
    Public Property 地址O As String
    Public Property 郵地區號O As String
    Public Property 戶籍地址 As String
    Public Property 戶籍地郵地區號 As String
    Public Property 國籍 As String
    Public Property 家戶病患 As Nullable(Of Short)
    Public Property 巡迴註記 As Nullable(Of Short)
    Public Property 家戶會員責任醫師代號 As String
    Public Property 預產期 As String
    Public Property 癌登否 As Nullable(Of Short)
    Public Property 統一編號 As String
    Public Property 父或母身份證字號 As String
    Public Property 父或母counter As Nullable(Of Integer)
    Public Property 同胎次序 As Nullable(Of Integer)
    Public Property 曾經接種流感疫苗 As Nullable(Of Short)
    Public Property 教育程度代碼 As Nullable(Of Short)
    Public Property 宗教信仰代碼 As Nullable(Of Short)
    Public Property 家戶收案日期 As String
    Public Property 緊急聯絡人關係 As String
    Public Property 介紹醫師 As String
    Public Property 最新子宮頸檢查日期 As String
    Public Property 最新子宮頸檢查醫院 As String
    Public Property 最後一次月經日期 As String
    Public Property 平均經期天數 As Nullable(Of Short)
    Public Property 依附父或母生日 As String
    Public Property 前家戶病患 As Nullable(Of Short)
    Public Property 下次產檢日期 As String
    Public Property 照護網 As String
    Public Property 照護衛教 As String
    Public Property 影像序號 As String
    Public Property 病人安全註記 As String
    Public Property 抗體 As String
    Public Property 代謝症候群收案註記 As String
    Public Property 重病診斷1 As String
    Public Property 重病診斷2 As String
    Public Property 重病診斷3 As String
    Public Property 重病診斷4 As String
    Public Property 重病診斷5 As String
    Public Property 重病診斷6 As String
    Public Property 最近修改過敏日 As String
    Public Property 美容會員 As Nullable(Of Short)
    Public Property 重病紙卡診斷1 As String
    Public Property 重病紙卡診斷2 As String
    Public Property 重病紙卡診斷3 As String
    Public Property 重病紙卡診斷4 As String
    Public Property 重病紙卡診斷5 As String
    Public Property 重病紙卡診斷6 As String
    Public Property 殘障否 As Nullable(Of Short)
    Public Property 健保卡片號碼 As String
    Public Property 最新成人老人健檢日期 As String
    Public Property 最新成人老人健檢醫院 As String
    Public Property 重病卡生效日2 As String
    Public Property 重病卡生效日3 As String
    Public Property 重病卡生效日4 As String
    Public Property 重病卡生效日5 As String
    Public Property 重病卡生效日6 As String
    Public Property 重大傷病效期2 As String
    Public Property 重大傷病效期3 As String
    Public Property 重大傷病效期4 As String
    Public Property 重大傷病效期5 As String
    Public Property 重大傷病效期6 As String
    Public Property 養護機構名稱 As String
    Public Property 養護機構代號 As String
    Public Property 重病IC卡生效日1 As String
    Public Property 重病IC卡生效日2 As String
    Public Property 重病IC卡生效日3 As String
    Public Property 重病IC卡生效日4 As String
    Public Property 重病IC卡生效日5 As String
    Public Property 重病IC卡生效日6 As String
    Public Property 重病IC卡效期1 As String
    Public Property 重病IC卡效期2 As String
    Public Property 重病IC卡效期3 As String
    Public Property 重病IC卡效期4 As String
    Public Property 重病IC卡效期5 As String
    Public Property 重病IC卡效期6 As String
    Public Property MIPHR會員等級 As String
    Public Property 照護族群 As Nullable(Of Short)
    Public Property 最新糞便檢查日期 As String
    Public Property 最新糞便檢查醫院 As String
    Public Property 家戶結案日期 As String
    Public Property 最新乳篩檢查日期 As String
    Public Property 最新乳篩檢查醫院 As String
    Public Property 家戶結案原因代碼 As Nullable(Of Short)
    Public Property 證件繳交 As String
    Public Property 最新口腔篩檢日期 As String
    Public Property 最新口腔篩檢醫院 As String
    Public Property 抽菸否 As Nullable(Of Short)
    Public Property 檳榔否 As Nullable(Of Short)
    Public Property 骨科備註 As String
    Public Property 已戒檳榔 As Nullable(Of Short)
    Public Property 無嚼檳榔及吸菸 As Nullable(Of Short)
    Public Property 口篩填選日期 As String
    Public Property 依病人為中心整合照護 As Nullable(Of Short)
    Public Property 上次呼吸器日期 As String
    Public Property 器官安寧註記 As String
    Public Property 最近30天內超過100支 As Nullable(Of Short)
    Public Property 管制病歷註記 As Nullable(Of Short)
    Public Property 油症註記 As String
    Public Property 過敏原5 As String
    Public Property 過敏原6 As String
    Public Property 過敏原7 As String
    Public Property 過敏原8 As String
    Public Property 照護機構入住日期 As String
    Public Property 照護機構離院日期 As String
    Public Property 過去病史 As String
    Public Property 家族史 As String
    Public Property 健康行為 As String
    Public Property 旅遊史 As String
    Public Property 住診顯示全名 As Nullable(Of Short)
    Public Property APP密碼 As String
    Public Property 緊急聯絡人手機 As String
    Public Property 替代役男有效起日 As String
    Public Property 替代役男有效迄日 As String
    Public Property 矯正機關代號 As String
    Public Property 矯正機關名稱 As String
    Public Property 醫缺地區 As Nullable(Of Short)
    Public Property 腦血管疾病診斷日 As String
    Public Property 已戒菸 As Nullable(Of Short)
    Public Property 自述血型代碼 As Nullable(Of Short)
    Public Property 最近看診醫師 As String
    Public Property 禁止預掛 As Nullable(Of Short)
    Public Property 器官安寧註記日期時間 As String
    Public Property 指定醫師 As String
    Public Property 指定美容師 As String
    Public Property 安寧修改經手記錄 As String
    Public Property 器官安寧圖片路徑 As String
    Public Property 安寧代碼 As Nullable(Of Short)
    Public Property 是否勸戒菸 As String
    Public Property 特殊備註 As String
    Public Property 病史獲取對象 As String
    Public Property 同意書起日 As String
    Public Property 同意書迄日 As String
    Public Property 糖尿病照護 As Nullable(Of Short)
    Public Property 自選病人 As Nullable(Of Short)
    Public Property 最後體重衛教日期 As String
    Public Property 血液陽性反應 As Nullable(Of Short)
    Public Property 血液陽性種類 As String
    Public Property 主治醫師 As String
    Public Property 外文姓名 As String
    Public Property 他國身份證 As String
    Public Property 他國電話 As String
    Public Property 胚胎培養 As String
    Public Property 性行為否 As Nullable(Of Short)

End Class
