'------------------------------------------------------------------------------
' <auto-generated>
'    這個程式碼是由範本產生。
'
'    對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
'    如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class 院所資料檔
    Public Property ts As Byte()
    Public Property Counter As Integer
    Public Property 院所名稱 As String
    Public Property 醫院等級代碼 As Nullable(Of Short)
    Public Property 院所科別代碼 As Nullable(Of Short)
    Public Property 院所負責人 As String
    Public Property 院所代號 As String
    Public Property 院所地址 As String
    Public Property 院所電話 As String
    Public Property 醫院類別代碼 As Nullable(Of Short)
    Public Property 居家照護代號 As String
    Public Property 居家照護負責人 As String
    Public Property 牙醫院所代號 As String
    Public Property 牙醫院所名稱 As String
    Public Property 院所郵遞區號 As String
    Public Property 藥局代號 As String
    Public Property 藥局名稱 As String
    Public Property 藥局地址 As String
    Public Property 藥局負責人 As String
    Public Property 藥局電話 As String
    Public Property 藥局申報藥師代號 As String
    Public Property 藥局申報藥師姓名 As String
    Public Property 傳真號碼 As String
    Public Property 電子信箱 As String
    Public Property 分機號碼 As String
    Public Property 所屬健保分局代號 As String
    Public Property 康復之家代號 As String
    Public Property 康復之家負責人 As String
    Public Property 北市醫院所代碼 As String
    Public Property 服務公司 As String
    Public Property 開業執照號碼 As String
    Public Property 英文院所名稱 As String
    Public Property 英文院所地址 As String
    Public Property 網路掛號 As String
    Public Property 語音掛號 As String
    Public Property 居家照護院所名稱 As String
    Public Property 口腔癌聯絡人姓名 As String
    Public Property 口腔癌聯絡人電話 As String
    Public Property 口腔癌回覆報告電子信箱 As String
    Public Property 院所OID As String
    Public Property 電子病歷檔案產生目錄 As String
    Public Property 啟用電子病歷日期 As String
    Public Property 電子病歷申報檔案產生目錄 As String
    Public Property 配合檢驗機構代號 As String
    Public Property 醫缺地區 As Nullable(Of Short)
    Public Property 電子病歷資料庫連結字串 As String
    Public Property 正式啟用ICD10日期 As String
    Public Property 住診正式啟用ICD10日期 As String
    Public Property 院所專屬體系 As String

End Class
